application: freelancehours-zemanel
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  login: admin

- url: /.*
  script: wsgi.app
  login: admin
  secure: always

skip_files: |
  ^(.*/)?(
  (app\.yaml)|
  (app\.yml)|
  (index\.yaml)|
  (index\.yml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*/RCS/.*)|
  (\..*)|
  (node_modules)|
  )$

libraries:
- name: django
  version: "1.3"